# Generated by Django 3.2.1 on 2021-05-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_cosde',
            new_name='zip_code',
        ),
    ]
